replicaCount: 1

image:
  pactImageRepository: pactfoundation/pact-broker
  pactImageTag: 2.38.1-1
  pullPolicy: IfNotPresent

service:
  name: pact-broker
  type: ClusterIP
  externalPort: 80

pact:
  port: 9292 # Container port


# See default values here: https://github.com/helm/charts/blob/master/stable/postgresql/values.yaml
postgresql:
  # Connection parameters for postgresql
  postgresqlHost: pact-broker-postgresql
  postgresqlUsername: pactbroker
  postgresqlPassword: pactbroker
  postgresqlDatabase: pactbroker

  ## Use the PostgreSQL chart dependency. Set to false if bringing your own PostgreSQL.
  enabled: true
  ## Enable PostgreSQL persistence using Persistent Volume Claims.
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 8Gi

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: pact-broker.local
      paths: []

  tls: []
  #  - secretName: pact-broker-tls
  #    hosts:
  #      - pact-broker.local

resources:
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi
