apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.pactImageRepository | lower }}:{{ .Values.image.pactImageTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.pact.port }}
          env:
            - name: PACT_BROKER_DATABASE_HOST
              value: {{ .Values.postgresql.postgresqlHost | default "localhost" }}
            - name: PACT_BROKER_DATABASE_NAME
              value: {{ .Values.postgresql.postgresqlDatabase }}
            - name: PACT_BROKER_DATABASE_USERNAME
              value: {{ .Values.postgresql.postgresqlUsername }}
            - name: PACT_BROKER_DATABASE_PASSWORD
              value: {{ .Values.postgresql.postgresqlPassword }}
            - name: PACT_BROKER_PORT
              value: {{ .Values.pact.port | default 9292 | quote }}

          resources:
{{ toYaml .Values.resources | indent 12 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
